actions

diff --git a/.github/workflows/server.yaml b/.github/workflows/server.yaml
--- a/.github/workflows/server.yaml
+++ b/.github/workflows/server.yaml
@@ -63,6 +63,8 @@ jobs:
       - name: Test
         run: npm run test
 
+      - run: exit 1
+
   release:
     if: |
       github.event_name != 'pull_request' &&
@@ -210,6 +212,11 @@ jobs:
         run: |
           echo "BUILD_URL=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
 
+      - name: Assign NOTIFICATION
+        shell: bash
+        run: |
+          echo "NOTIFICATION='{"level": "error", "message": "Server [build $BUILD_GROUP_NUMBER]( $BUILD_URL) deployment failed", "text": "Server <$BUILD_URL|build $BUILD_GROUP_NUMBER> deployment failed"}'" >> $GITHUB_ENV
+
       - name: Delete release on failure
         uses: dev-drprasad/delete-tag-and-release@v0.1.3
         if: |
@@ -228,7 +235,14 @@ jobs:
           contains(github.ref, 'refs/heads/release'))
         uses: Ilshidur/action-slack@2.0.2
         env:
-          SLACK_CUSTOM_PAYLOAD: '{"level": "error", "message": "Server [build {{ BUILD_GROUP_NUMBER }}]({{ BUILD_URL }}) deployment failed", "text": "Server <{{ BUILD_URL }}|build {{ BUILD_GROUP_NUMBER }}> deployment failed"}'
+          SLACK_CUSTOM_PAYLOAD: '{{ NOTIFICATION }}'
+
+      - name: Gitter notify
+        uses: fjogeleit/http-request-action@master
+        with:
+          url: ${{ secrets.GITTER_URL }}
+          data: ${{ NOTIFICATION }}
+          method: 'POST'
         
 
 
